import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'
import { clientsClaim } from 'workbox-core'

// vite.config.js 의 registerType 이 'prompt' 이므로 여기서 skipWaiting() 을 바로 부르면 안 된다.
// 그러면 새 버전이 배포될 때마다 사용자가 앱을 쓰는 도중 예고 없이 페이지가 새로고침된다.
// 대신 SWUpdatePrompt 의 "업데이트" 버튼 -> workbox-window 가 보내는 이 메시지를 기다린다.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

clientsClaim()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// SPA 네비게이션 폴백.
// injectManifest 전략은 navigateFallback 을 자동으로 넣어주지 않는다. 이게 없으면
// 오프라인에서 /list, /calendar 같은 경로를 새로고침·딥링크로 열 때 프리캐시된
// index.html 에 닿지 못하고 브라우저 오프라인 화면이 뜬다.
registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'), {
    denylist: [
      // 해지 가이드는 빌드 시 생성되는 정적 HTML 이다. SPA 셸로 덮어쓰면 통째로 죽는다.
      /^\/guide\//,
      /^\/404\.html$/,
      /^\/assets\//,
      // sitemap.xml, robots.txt 처럼 확장자가 붙은 실제 파일은 서버로 그대로 보낸다.
      /\/[^/?]+\.[^/?]+$/,
    ],
  })
)

// Pretendard 는 유니코드 범위별로 잘린 다이내믹 서브셋이라 조각 수가 많고,
// 어떤 조각이 필요한지는 화면에 실제로 그려진 글자에 따라 달라진다.
// 프리캐시(설치 시 전량 다운로드)에는 맞지 않으므로 쓰인 조각만 런타임에 캐시한다.
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'font-subsets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 60 * 24 * 365,
        purgeOnQuotaError: true,
      }),
    ],
  })
)

// Handle Push Notification
self.addEventListener('push', (event) => {
  // 페이로드가 없는 push 나 JSON 이 아닌 본문이 오면 event.data.json() 이 던진다.
  // 여기서 예외가 나면 알림이 아예 뜨지 않으므로 반드시 막아야 한다.
  let data = {}
  try {
    data = event.data ? event.data.json() : {}
  } catch {
    data = { body: event.data ? event.data.text() : '' }
  }

  const options = {
    body: data.body,
    icon: '/favicon-96x96.png',
    badge: '/favicon-96x96.png',
    vibrate: [200, 100, 200],
    data: {
      url: data.url || '/'
    }
  }

  event.waitUntil(
    self.registration.showNotification(data.title || '구독노트', options)
  )
})

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
  const notification = event.notification;
  notification.close();

  // 알림에 데이터로 넣은 URL이 있으면 사용, 없으면 루트
  const urlToOpen = (notification.data && notification.data.url) ? notification.data.url : '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // 1. 이미 앱이 열려있다면 해당 창을 포커스하고 페이지 이동
      for (const client of clientList) {
        if ('focus' in client) {
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      // 2. 앱이 닫혀있다면 새로 열기
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
